ASUWebPlatforms/webspark-module-webspark_blocks

webspark_blocks.module

These are your changes Georgi, I just commit them to the correct repository.

WS2-323: Alter submit buttons

---

js/anchor-menu.js

WS2-298: Anchor menu fix for the admin menu.

---

config/install/core.entity_form_display.block_content.hero.default.yml
config/install/core.entity_view_display.block_content.hero.default.yml
config/install/field.field.block_content.hero.field_sub_heading.yml
config/install/field.storage.block_content.field_sub_heading.yml

This PR adds a new field to the Hero for a subheading and reorders the fields logically to reflect the change.

ws2-480: Add new sub heading field to hero and re-order fields.

---

config/install/field.storage.block_content.field_background_color.yml

Update color names to recently determined names

WS2-545: Update colors to recently determined names.

---

config/install/core.entity_form_display.block_content.banner.default.yml
config/install/field.field.block_content.banner.field_banner_background_color.yml
config/install/field.storage.block_content.field_banner_background_color.yml

Update colour selection field to allow color icons to be shown next to radio buttons for notifications.

WS2-370 Update colour selection field

---

config/install/field.storage.block_content.field_color.yml
config/install/field.storage.paragraph.field_color_options.yml

Update accordion to latest color names.

WS2-528: Accordion update colors to latest names.

---

js/anchor-menu.js
templates/webspark-blocks-anchor-menu.html.twig

Adding .container to support full-width layout, adjusting JS to work better with offset, more consistent offset top reading from nav element.

UDS-664: Resolving anchor menu issues.

---

config/install/core.entity_form_display.block_content.hero.default.yml
config/install/core.entity_view_display.block_content.hero.default.yml
config/install/field.field.block_content.hero.field_sub_heading_background.yml
config/install/field.storage.block_content.field_cta.yml
config/install/field.storage.block_content.field_sub_heading_background.yml

Extra fields to support new background color for subheading and allow multiple buttons.

ws2-647: Extra fields to support new background color for subheading.

---

config/install/field.storage.block_content.field_cta.yml

Revert cardinality to 1 for CTA field.

Revert cardinality to 1 for CTA field.

---

config/install/field.storage.paragraph.field_tooltip_background.yml

Updated color names for background selector.

WS2-601: Update color names in tooltip.

---

config/install/field.storage.block_content.field_banner_background_color.yml

Change color names for background selector on notifications.

WS2-393: Update color names for background selector.

---

config/install/block_content.type.image_background_with_cta.yml
config/install/core.entity_form_display.block_content.image_and_text_block.default.yml
config/install/core.entity_form_display.block_content.image_background_with_cta.default.yml
config/install/core.entity_view_display.block_content.content_image.default.yml
config/install/core.entity_view_display.block_content.image_background_with_cta.default.yml
config/install/field.field.block_content.image_and_text_block.field_anchor_menu_settings.yml
config/install/field.field.block_content.image_and_text_block.field_spacing_bottom.yml
config/install/field.field.block_content.image_and_text_block.field_spacing_top.yml
config/install/field.field.block_content.image_background_with_cta.field_anchor_menu_settings.yml
config/install/field.field.block_content.image_background_with_cta.field_cta.yml
config/install/field.field.block_content.image_background_with_cta.field_heading.yml
config/install/field.field.block_content.image_background_with_cta.field_media.yml
config/install/field.field.block_content.image_background_with_cta.field_spacing_bottom.yml
config/install/field.field.block_content.image_background_with_cta.field_spacing_top.yml

Fix config for image_and_text_block and content_image
Add content section: image_background_with_cta

Content sections

---

config/install/core.entity_form_display.block_content.card_and_image.default.yml
config/install/core.entity_form_display.paragraph.card_with_icon.card_and_image.yml
config/install/core.entity_form_mode.paragraph.card_and_image.yml

Create a new form display mode for the card with icon paragraph.
Set the maxlength on the body field for the new form mode to 190.
Use the new form mode on card and image component for the card with icon paragraph field.

Add maxlength to card and image component card. @See WS2-741.

---

webspark_blocks.info.yml

I discovered a dependency error for this module when I tested. If you need this, you can merge it.

Fix dependecy error at profile install.

---

config/install/field.storage.block_content.field_background_color.yml

We need to make a function to migrate the data before we remove this.

Fix the update for the field background color.

---

config/install/core.entity_form_display.media.image.default.yml
config/install/field.field.media.cropped_image_sqare.field_media_image.yml
config/install/field.field.media.cropped_image_wide.field_media_image.yml
config/install/field.field.media.image.field_media_image.yml
config/install/field.field.media.image_block_images.field_media_image.yml
config/install/field.field.media.story_hero.field_media_image.yml

@duarte-daniela @mlsamuelson this sets the Alt field as optional.
Ref.: https://asudev.jira.com/browse/WS2-1009

WS2-1009: Set image alt field as optional.

---

config/install/core.entity_form_display.block_content.divider.default.yml
config/install/core.entity_view_display.block_content.divider.default.yml
config/install/field.field.block_content.divider.field_divider_type.yml
config/install/field.storage.block_content.field_divider_type.yml
webspark_blocks.install

@duarte-daniela @mlsamuelson this sets the Divider block type.
Ref.: https://asudev.jira.com/browse/WS2-1108

WS2-1108: Set Divider type.

---

config/install/core.entity_form_display.block_content.card_and_image.default.yml
config/install/core.entity_view_display.block_content.card_and_image.default.yml
config/install/field.field.block_content.card_and_image.field_parallax.yml
config/install/field.storage.block_content.field_parallax.yml
webspark_blocks.install

@duarte-daniela @mlsamuelson this adds the parallax effect for the `Card and Image` component.
Ref.: https://asudev.jira.com/browse/WS2-997

WS2-997: Card and Image parallax.

---

config/install/media.type.remote_video.yml
webspark_blocks.install

@duarte-daniela @mlsamuelson this removes Vimeo as an remote video provider.
Ref.: https://asudev.jira.com/browse/WS2-591?focusedCommentId=1384149

WS2-591: Remove Vimeo as an allowed provider.

---

config/install/block_content.type.webform.yml
config/install/core.entity_form_display.block_content.webform.default.yml
config/install/core.entity_view_display.block_content.webform.default.yml
config/install/field.field.block_content.webform.field_anchor_menu_settings.yml
config/install/field.field.block_content.webform.field_spacing_bottom.yml
config/install/field.field.block_content.webform.field_spacing_top.yml
config/install/field.field.block_content.webform.field_webform.yml
config/install/field.storage.block_content.field_webform.yml

@duarte-daniela @mlsamuelson this adds the Webform custom block where Appearance Settings could be set

WS2-1144: Create custom webform block.

---

config/install/core.entity_form_display.paragraph.tab_content.default.yml
config/install/core.entity_view_display.paragraph.tab_content.default.yml
config/install/field.field.paragraph.tab_content.field_blocks.yml
config/install/field.storage.paragraph.field_blocks.yml

@duarte-daniela @mlsamuelson this adds the block_field related functionality.
Ref.: https://asudev.jira.com/browse/WS2-1142

WS2-1142: Enable block_field module functionality.

---

config/install/field.field.block_content.card_and_image.field_media.yml
config/install/field.field.block_content.card_image_and_content.field_media.yml
config/install/field.field.block_content.content_image.field_media.yml
config/install/field.field.block_content.hero.field_media.yml
config/install/field.field.block_content.image.field_media.yml
config/install/field.field.block_content.image_and_text_block.field_media.yml
config/install/field.field.block_content.image_background_with_cta.field_media.yml
config/install/field.field.block_content.testimonial_on_image_background.field_media.yml
config/install/field.field.paragraph.blockquote.field_media.yml
config/install/field.field.paragraph.card.field_media.yml
config/install/field.field.paragraph.card_degree.field_media.yml
config/install/field.field.paragraph.card_event.field_media.yml
config/install/field.field.paragraph.card_media.field_media.yml
config/install/field.field.paragraph.card_story.field_media.yml
config/install/field.field.paragraph.gallery_image.field_media.yml
config/install/field.field.paragraph.testimonial.field_media.yml

@duarte-daniela @mlsamuelson this adds help text related to recommended image sizes.
Ref.: https://asudev.jira.com/browse/WS2-1146

WS2-1146: Add suggested image dimensions.

---

config/install/core.entity_form_display.media.cropped_image_sqare.default.yml
config/install/core.entity_form_display.media.cropped_image_sqare.media_library.yml
config/install/core.entity_form_display.media.cropped_image_wide.default.yml
config/install/core.entity_form_display.media.cropped_image_wide.media_library.yml
config/install/core.entity_form_display.media.image_block_images.default.yml
config/install/core.entity_form_display.media.image_block_images.media_library.yml
config/install/core.entity_form_display.media.story_hero.default.yml
config/install/core.entity_form_display.media.story_hero.media_library.yml

@duarte-daniela @mlsamuelson this adds the Decorative Image option.
Ref.: https://asudev.jira.com/browse/WS2-1009?focusedCommentId=1395016

WS2-1009: Set Decorative Image option.

---

webspark_blocks.install

WS2-1209 deletes 9001 and 9003 -- I'm adding 9002 for this PR. Let me know if 9002 should remain.

Removed updates 9001, 9002, 9003 per WS2-1209

---

config/install/core.entity_form_display.paragraph.card.carousel_card.yml
config/install/core.entity_form_display.paragraph.card.default.yml
config/install/core.entity_form_display.paragraph.card_degree.carousel_card.yml
config/install/core.entity_form_display.paragraph.card_degree.default.yml
config/install/core.entity_form_display.paragraph.card_story.carousel_card.yml
config/install/core.entity_form_display.paragraph.card_story.default.yml
config/install/core.entity_form_display.paragraph.card_with_icon.card_and_image.yml
webspark_blocks.install

JIRA: https://asudev.jira.com/browse/WS2-1324
This config update removes the character limits from cards.

WS2-1324: Remove character limits from Cards

---

config/install/core.entity_form_display.block_content.video_hero.default.yml

Missed this yaml when copying the config export files.

Fix form display for video hero block.

---

config/install/field.field.block_content.video_hero.field_background_image.yml

See: https://asudev.jira.com/browse/WS2-1373

WS2-1373: Update Video Hero poster descriptive text

---

src/Plugin/Block/AnchorMenuBlock.php

WS2-1451: Added description into AnchorMenuBlock form.

---

config/install/core.entity_form_display.paragraph.testimonial.default.yml
webspark_blocks.install

Ticket: https://asudev.jira.com/browse/WS2-1468

WS2-1468: Hide guideline text for formatted text field in Testimonial paragraph

---

config/install/image.style.image.yml
webspark_blocks.install

Ticket: https://asudev.jira.com/browse/WS2-1524

WS2-1524: Adding new image style
